micronaut:
  application:
    name: taskManager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/main
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
jpa.default.properties.hibernate.hbm2ddl.auto: update